"""Tests for the KPI layer.

Two kinds of check:
  1. Cross-implementation: the Python reference (src/kpis.py) must reproduce, to the paisa, what the
     dashboard's own JavaScript engine computes (fixture generated by src/engine_reference.js).
  2. Identities that must hold in any month, on the real processed data.
"""
import json
import shutil
import subprocess
from pathlib import Path

import pandas as pd
import pytest

from src import kpis

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = json.loads((ROOT / "tests" / "fixtures" / "engine_reference.json").read_text())
CASES = {c["name"]: c for c in FIXTURE["cases"]}


@pytest.fixture(scope="module")
def model():
    return kpis.build_model()


def window(case):
    p = pd.Timestamp(case["filter"]["period"], unit="ms")
    return kpis.month_window(p.year, p.month)


def scope(case):
    f = case["filter"]
    return dict(customer_orders_only=f["scope"] == "CUSTOMER", cat=f["cat"], customer_id="ALL" if f["cust"] == "ALL" else f["cust"][2:])


@pytest.mark.parametrize("name", list(CASES))
def test_net_sales_matches_dashboard_engine(model, name):
    c = CASES[name]
    assert kpis.net_sales(model, *window(c), **scope(c)) == pytest.approx(c["net"], abs=0.01)


@pytest.mark.parametrize("name", list(CASES))
def test_orders_received_matches_dashboard_engine(model, name):
    c = CASES[name]
    assert kpis.orders_received(model, *window(c), **scope(c)) == pytest.approx(c["intake"], abs=0.01)


@pytest.mark.parametrize("name", list(CASES))
def test_on_time_delivery_matches_dashboard_engine(model, name):
    c = CASES[name]
    otd, n = kpis.on_time_delivery(model, *window(c), **scope(c))
    assert n == c["otd_lines"]
    assert otd == pytest.approx(c["otd"], abs=1e-9)


@pytest.mark.parametrize("name", ["Sep 2026 all products", "Aug 2026 ribbons", "Jun 2026 incl. HQ / stock"])
def test_open_order_book_matches_dashboard_engine(model, name):
    c = CASES[name]
    book = kpis.open_order_book(model, **scope(c))
    assert book["open_value"] == pytest.approx(c["open_value"], abs=0.01)
    assert book["open_lines"] == c["open_lines"]
    assert book["overdue_value"] == pytest.approx(c["overdue_value"], abs=0.01)


def test_book_to_bill_is_orders_over_sales(model):
    c = CASES["Sep 2026 all products"]
    assert kpis.book_to_bill(model, *window(c)) == pytest.approx(c["book_to_bill"], rel=1e-9)
    assert kpis.book_to_bill(model, *window(c)) == pytest.approx(c["intake"] / c["net"], rel=1e-9)


def test_ribbon_plus_bow_sales_equal_total(model):
    start, end = kpis.month_window(2026, 8)
    total = kpis.net_sales(model, start, end)
    parts = kpis.net_sales(model, start, end, cat="RIBBON") + kpis.net_sales(model, start, end, cat="BOW")
    assert parts == pytest.approx(total, abs=0.01)


def test_customer_sales_add_up_to_total(model):
    start, end = kpis.month_window(2026, 8)
    _, s = kpis._scope(model)
    w = s[(s.invoice_date >= start) & (s.invoice_date <= end) & s.net.notna()]
    assert w.groupby("customer_id").net.sum().sum() == pytest.approx(kpis.net_sales(model, start, end), abs=0.01)


def test_internal_orders_never_count_as_customer_sales(model):
    s = model.sales
    assert not s[s.order_type.isin(["HQ STOCK TRANSFER", "INVENTORY STOCK ORDER"])].counts.any()
    assert not s[s.document_type == "STOCK TRANSFER DC"].counts.any()


def test_credit_notes_reduce_sales(model):
    cn = model.sales[(model.sales.document_type == "CREDIT NOTE") & model.sales.goods.notna()]
    assert (cn.goods <= 0).all()


def test_charges_are_billed_once_per_order(model):
    charged = model.sales[model.sales.charges > 0]
    assert not charged.duplicated("order_no").any()


def test_dispatched_never_negative_and_status_consistent(model):
    o = model.orders
    assert (o.dq >= 0).all()
    assert set(o.status.dropna().unique()) <= {"OPEN", "PARTIAL", "COMPLETED", "CANCELLED", "DOUBLE ENTRY", "ON HOLD", "SHORT-CLOSED", "CLOSED - OLD DATA"}
    assert (o[o.status == "OPEN"].dq == 0).all()


@pytest.mark.skipif(shutil.which("node") is None, reason="node not installed")
def test_fixture_is_current_with_the_dashboard_engine():
    """The committed fixture must equal a fresh run of the engine embedded in dashboard/index.html."""
    out = subprocess.run(["node", str(ROOT / "src" / "engine_reference.js")], capture_output=True, text=True, check=True).stdout
    assert json.loads(out) == FIXTURE


def test_trend_follows_the_compare_choice():
    """With 'vs previous period' each bar's comparison is the bar before it (it used to be last year regardless)."""
    t = FIXTURE["prev_trend"]
    assert t["last_comparison"] == pytest.approx(t["previous_bar_net"], abs=0.01)


def test_seasonality_months_match_python_reference(model):
    """Every complete month the seasonality chart draws equals the Python net sales for that month."""
    season = FIXTURE["season"]
    assert season[0]["y"] == 2025 and season[0]["m"] == 3        # starts at the first reliable month, April 2025
    for r in season:
        a, b = kpis.month_window(r["y"], r["m"] + 1)
        assert kpis.net_sales(model, a, b) == pytest.approx(r["net"], abs=0.01)
